# Generated by Django 4.2.28 on 2026-03-05 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0005_remove_inscripcionalumno_alumno_and_more'),
        ('asignacion_curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.alumno')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion_curso.asignacioncurso')),
            ],
            options={
                'db_table': 'notas',
            },
        ),
    ]
