# Generated by Django 4.2.28 on 2026-03-04 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catedratico', '0001_initial'),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=50)),
                ('catedratico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catedratico.catedratico')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
            ],
            options={
                'db_table': 'asignacion_curso',
            },
        ),
    ]
