# Generated by Django 4.2.28 on 2026-03-04 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0005_remove_inscripcionalumno_alumno_and_more'),
        ('asignacion_curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.alumno')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion_curso.asignacioncurso')),
            ],
            options={
                'db_table': 'inscripcion_alumno',
            },
        ),
    ]
