# Generated by Django 4.2.28 on 2026-02-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumno',
            table='alumno',
        ),
    ]
