# Generated by Django 4.2.28 on 2026-03-04 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0003_catedratico_curso_notas_inscripcionalumno_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asignacioncurso',
            table='asignacion_curso',
        ),
        migrations.AlterModelTable(
            name='catedratico',
            table='catedratico',
        ),
        migrations.AlterModelTable(
            name='curso',
            table='curso',
        ),
        migrations.AlterModelTable(
            name='inscripcionalumno',
            table='inscripcion_alumno',
        ),
        migrations.AlterModelTable(
            name='notas',
            table='notas',
        ),
    ]
