# Generated by Django 4.2.28 on 2026-03-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0004_alter_asignacioncurso_table_alter_catedratico_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcionalumno',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='inscripcionalumno',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='curso',
        ),
        migrations.DeleteModel(
            name='AsignacionCurso',
        ),
        migrations.DeleteModel(
            name='Catedratico',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='InscripcionAlumno',
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
    ]
